// File generated by FlutterFire CLI — do not edit by hand.
// Run from admin/: dart pub global run flutterfire_cli:flutterfire configure
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux — '
          'run FlutterFire CLI from admin/ with linux if needed.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7KXndHUs1chiYaNAy5EXSZ7qXBnmHLJs',
    appId: '1:65010316831:web:34438ca504bdd496d6c72a',
    messagingSenderId: '65010316831',
    projectId: 'payment-checker-4049e',
    authDomain: 'payment-checker-4049e.firebaseapp.com',
    storageBucket: 'payment-checker-4049e.firebasestorage.app',
    measurementId: 'G-265PN8Z2M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx9KrEf16ys9nzFlHvOCwAPA19XqhVK7Y',
    appId: '1:65010316831:android:2e7592098d1393fbd6c72a',
    messagingSenderId: '65010316831',
    projectId: 'payment-checker-4049e',
    storageBucket: 'payment-checker-4049e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZvHD_F72iH2yZVmTDH_0Z-VKKsidPDBU',
    appId: '1:65010316831:ios:70483d158c0b04cad6c72a',
    messagingSenderId: '65010316831',
    projectId: 'payment-checker-4049e',
    storageBucket: 'payment-checker-4049e.firebasestorage.app',
    iosBundleId: 'com.example.paymentCheckerAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZvHD_F72iH2yZVmTDH_0Z-VKKsidPDBU',
    appId: '1:65010316831:ios:70483d158c0b04cad6c72a',
    messagingSenderId: '65010316831',
    projectId: 'payment-checker-4049e',
    storageBucket: 'payment-checker-4049e.firebasestorage.app',
    iosBundleId: 'com.example.paymentCheckerAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7KXndHUs1chiYaNAy5EXSZ7qXBnmHLJs',
    appId: '1:65010316831:web:34438ca504bdd496d6c72a',
    messagingSenderId: '65010316831',
    projectId: 'payment-checker-4049e',
    authDomain: 'payment-checker-4049e.firebaseapp.com',
    storageBucket: 'payment-checker-4049e.firebasestorage.app',
    measurementId: 'G-265PN8Z2M7',
  );
}
